# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file.

## Objectives
You will be able to:

- Use pandas to import data from a CSV and and an Excel spreadsheet  

##  Loading Files with Summary or Meta Data

Load either of the files `'Zipcode_Demos.csv'` or `'Zipcode_Demos.xlsx'`. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled `'Data'`.

In [1]:
# Import pandas using the standard alias
import pandas as pd

In [7]:
# Import the file and print the first 5 rows
df = pd.read_csv("./Data/Zipcode_Demos.csv", encoding = "latin-1")

In [3]:
# Print the last 5 rows of df
print(df.tail())

     0 Average Statistics Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
52  53              10006          6          2       0.33          4
53  54              10007          1          0          0          1
54  55              10009          2          0          0          2
55  56              10010          0          0          0          0
56  57              10011          3          2       0.67          1

   Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
52       0.67          0          0          6  ...           6         100
53          1          0          0          1  ...           1         100
54          1          0          0          2  ...           2         100
55          0          0          0          0  ...           0           0
56       0.33          0          0          3  ...           3         100

   Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42 Unnamed: 43 Unnamed: 44  \
52           0           0           6           1           0           0
53           1           1           0           0           0           0
54           0           0           2           1           0           0
55           0           0           0           0           0           0
56           0           0           3           1           0           0

   Unnamed: 45 Unnamed: 46
52           6         100
53           1         100
54           2         100
55           0           0
56           3         100

[5 rows x 47 columns]

In [4]:
# What is going on with this data set? Anything unusual?
print(df.info())
print(df)

#The first 45 rows are unneccesary. They are empty except for an average column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 47 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   0                   57 non-null     int64
 1   Average Statistics  56 non-null     object
 2   Unnamed: 2          57 non-null     object
 3   Unnamed: 3          11 non-null     object
 4   Unnamed: 4          11 non-null     object
 5   Unnamed: 5          11 non-null     object
 6   Unnamed: 6          11 non-null     object
 7   Unnamed: 7          11 non-null     object
 8   Unnamed: 8          11 non-null     object
 9   Unnamed: 9          11 non-null     object
 10  Unnamed: 10         11 non-null     object
 11  Unnamed: 11         11 non-null     object
 12  Unnamed: 12         11 non-null     object
 13  Unnamed: 13         11 non-null     object
 14  Unnamed: 14         11 non-null     object
 15  Unnamed: 15         11 non-null     object
 16  Unnamed: 16         11 non-null     object
 17  Unnamed: 17         11 non-null     object
 18  Unnamed: 18         11 non-null     object
 19  Unnamed: 19         11 non-null     object
 20  Unnamed: 20         11 non-null     object
 21  Unnamed: 21         11 non-null     object
 22  Unnamed: 22         11 non-null     object
 23  Unnamed: 23         11 non-null     object
 24  Unnamed: 24         11 non-null     object
 25  Unnamed: 25         11 non-null     object
 26  Unnamed: 26         11 non-null     object
 27  Unnamed: 27         11 non-null     object
 28  Unnamed: 28         11 non-null     object
 29  Unnamed: 29         11 non-null     object
 30  Unnamed: 30         11 non-null     object
 31  Unnamed: 31         11 non-null     object
 32  Unnamed: 32         11 non-null     object
 33  Unnamed: 33         11 non-null     object
 34  Unnamed: 34         11 non-null     object
 35  Unnamed: 35         11 non-null     object
 36  Unnamed: 36         11 non-null     object
 37  Unnamed: 37         11 non-null     object
 38  Unnamed: 38         11 non-null     object
 39  Unnamed: 39         11 non-null     object
 40  Unnamed: 40         11 non-null     object
 41  Unnamed: 41         11 non-null     object
 42  Unnamed: 42         11 non-null     object
 43  Unnamed: 43         11 non-null     object
 44  Unnamed: 44         11 non-null     object
 45  Unnamed: 45         11 non-null     object
 46  Unnamed: 46         11 non-null     object
dtypes: int64(1), object(46)
memory usage: 21.1+ KB
None
     0                   Average Statistics          Unnamed: 2    Unnamed: 3  \
0    1                                  NaN                   0           NaN
1    2                    JURISDICTION NAME             10005.8           NaN
2    3                   COUNT PARTICIPANTS                 9.4           NaN
3    4                         COUNT FEMALE                 4.8           NaN
4    5                       PERCENT FEMALE               0.404           NaN
5    6                           COUNT MALE                 4.6           NaN
6    7                         PERCENT MALE               0.396           NaN
7    8                 COUNT GENDER UNKNOWN                   0           NaN
8    9               PERCENT GENDER UNKNOWN                   0           NaN
9   10                   COUNT GENDER TOTAL                 9.4           NaN
10  11                 PERCENT GENDER TOTAL                  80           NaN
11  12               COUNT PACIFIC ISLANDER                   0           NaN
12  13             PERCENT PACIFIC ISLANDER                   0           NaN
13  14                COUNT HISPANIC LATINO                   2           NaN
14  15              PERCENT HISPANIC LATINO               0.105           NaN
15  16                COUNT AMERICAN INDIAN                   0           NaN
16  17              PERCENT AMERICAN INDIAN                   0           NaN
17  18             COUNT ASIAN NON HISPANIC                 3.6           NaN
18  19           PERCENT ASIAN NON HISPANIC               0.437           NaN
19  20             COUNT WHITE NON HISPANIC                 0.8           NaN
20  21           PERCENT WHITE NON HISPANIC               0.036           NaN
21  22             COUNT BLACK NON HISPANIC                 2.6           NaN
22  23           PERCENT BLACK NON HISPANIC               0.181           NaN
23  24                COUNT OTHER ETHNICITY                 0.4           NaN
24  25              PERCENT OTHER ETHNICITY                0.04           NaN
25  26              COUNT ETHNICITY UNKNOWN                   0           NaN
26  27            PERCENT ETHNICITY UNKNOWN                   0           NaN
27  28                COUNT ETHNICITY TOTAL                 9.4           NaN
28  29              PERCENT ETHNICITY TOTAL                79.9           NaN
29  30       COUNT PERMANENT RESIDENT ALIEN                 0.5           NaN
30  31     PERCENT PERMANENT RESIDENT ALIEN               0.061           NaN
31  32                     COUNT US CITIZEN                 8.9           NaN
32  33                   PERCENT US CITIZEN               0.739           NaN
33  34           COUNT OTHER CITIZEN STATUS                   0           NaN
34  35         PERCENT OTHER CITIZEN STATUS                   0           NaN
35  36         COUNT CITIZEN STATUS UNKNOWN                   0           NaN
36  37       PERCENT CITIZEN STATUS UNKNOWN                   0           NaN
37  38           COUNT CITIZEN STATUS TOTAL                 9.4           NaN
38  39         PERCENT CITIZEN STATUS TOTAL                  80           NaN
39  40     COUNT RECEIVES PUBLIC ASSISTANCE                 2.3           NaN
40  41   PERCENT RECEIVES PUBLIC ASSISTANCE               0.151           NaN
41  42    COUNT NRECEIVES PUBLIC ASSISTANCE                 7.1           NaN
42  43  PERCENT NRECEIVES PUBLIC ASSISTANCE               0.649           NaN
43  44      COUNT PUBLIC ASSISTANCE UNKNOWN                   0           NaN
44  45    PERCENT PUBLIC ASSISTANCE UNKNOWN                   0           NaN
45  46        COUNT PUBLIC ASSISTANCE TOTAL                 9.4           NaN
46  47                    JURISDICTION NAME  COUNT PARTICIPANTS  COUNT FEMALE
47  48                                10001                  44            22
48  49                                10002                  35            19
49  50                                10003                   1             1
50  51                                10004                   0             0
51  52                                10005                   2             2
52  53                                10006                   6             2
53  54                                10007                   1             0
54  55                                10009                   2             0
55  56                                10010                   0             0
56  57                                10011                   3             2

        Unnamed: 4  Unnamed: 5    Unnamed: 6            Unnamed: 7  \
0              NaN         NaN           NaN                   NaN
1              NaN         NaN           NaN                   NaN
2              NaN         NaN           NaN                   NaN
3              NaN         NaN           NaN                   NaN
4              NaN         NaN           NaN                   NaN
5              NaN         NaN           NaN                   NaN
6              NaN         NaN           NaN                   NaN
7              NaN         NaN           NaN                   NaN
8              NaN         NaN           NaN                   NaN
9              NaN         NaN           NaN                   NaN
10             NaN         NaN           NaN                   NaN
11             NaN         NaN           NaN                   NaN
12             NaN         NaN           NaN                   NaN
13             NaN         NaN           NaN                   NaN
14             NaN         NaN           NaN                   NaN
15             NaN         NaN           NaN                   NaN
16             NaN         NaN           NaN                   NaN
17             NaN         NaN           NaN                   NaN
18             NaN         NaN           NaN                   NaN
19             NaN         NaN           NaN                   NaN
20             NaN         NaN           NaN                   NaN
21             NaN         NaN           NaN                   NaN
22             NaN         NaN           NaN                   NaN
23             NaN         NaN           NaN                   NaN
24             NaN         NaN           NaN                   NaN
25             NaN         NaN           NaN                   NaN
26             NaN         NaN           NaN                   NaN
27             NaN         NaN           NaN                   NaN
28             NaN         NaN           NaN                   NaN
29             NaN         NaN           NaN                   NaN
30             NaN         NaN           NaN                   NaN
31             NaN         NaN           NaN                   NaN
32             NaN         NaN           NaN                   NaN
33             NaN         NaN           NaN                   NaN
34             NaN         NaN           NaN                   NaN
35             NaN         NaN           NaN                   NaN
36             NaN         NaN           NaN                   NaN
37             NaN         NaN           NaN                   NaN
38             NaN         NaN           NaN                   NaN
39             NaN         NaN           NaN                   NaN
40             NaN         NaN           NaN                   NaN
41             NaN         NaN           NaN                   NaN
42             NaN         NaN           NaN                   NaN
43             NaN         NaN           NaN                   NaN
44             NaN         NaN           NaN                   NaN
45             NaN         NaN           NaN                   NaN
46  PERCENT FEMALE  COUNT MALE  PERCENT MALE  COUNT GENDER UNKNOWN
47             0.5          22           0.5                     0
48            0.54          16          0.46                     0
49               1           0             0                     0
50               0           0             0                     0
51               1           0             0                     0
52            0.33           4          0.67                     0
53               0           1             1                     0
54               0           2             1                     0
55               0           0             0                     0
56            0.67           1          0.33                     0

                Unnamed: 8          Unnamed: 9  ...  \
0                      NaN                 NaN  ...
1                      NaN                 NaN  ...
2                      NaN                 NaN  ...
3                      NaN                 NaN  ...
4                      NaN                 NaN  ...
5                      NaN                 NaN  ...
6                      NaN                 NaN  ...
7                      NaN                 NaN  ...
8                      NaN                 NaN  ...
9                      NaN                 NaN  ...
10                     NaN                 NaN  ...
11                     NaN                 NaN  ...
12                     NaN                 NaN  ...
13                     NaN                 NaN  ...
14                     NaN                 NaN  ...
15                     NaN                 NaN  ...
16                     NaN                 NaN  ...
17                     NaN                 NaN  ...
18                     NaN                 NaN  ...
19                     NaN                 NaN  ...
20                     NaN                 NaN  ...
21                     NaN                 NaN  ...
22                     NaN                 NaN  ...
23                     NaN                 NaN  ...
24                     NaN                 NaN  ...
25                     NaN                 NaN  ...
26                     NaN                 NaN  ...
27                     NaN                 NaN  ...
28                     NaN                 NaN  ...
29                     NaN                 NaN  ...
30                     NaN                 NaN  ...
31                     NaN                 NaN  ...
32                     NaN                 NaN  ...
33                     NaN                 NaN  ...
34                     NaN                 NaN  ...
35                     NaN                 NaN  ...
36                     NaN                 NaN  ...
37                     NaN                 NaN  ...
38                     NaN                 NaN  ...
39                     NaN                 NaN  ...
40                     NaN                 NaN  ...
41                     NaN                 NaN  ...
42                     NaN                 NaN  ...
43                     NaN                 NaN  ...
44                     NaN                 NaN  ...
45                     NaN                 NaN  ...
46  PERCENT GENDER UNKNOWN  COUNT GENDER TOTAL  ...
47                       0                  44  ...
48                       0                  35  ...
49                       0                   1  ...
50                       0                   0  ...
51                       0                   2  ...
52                       0                   6  ...
53                       0                   1  ...
54                       0                   2  ...
55                       0                   0  ...
56                       0                   3  ...

                   Unnamed: 37                   Unnamed: 38  \
0                          NaN                           NaN
1                          NaN                           NaN
2                          NaN                           NaN
3                          NaN                           NaN
4                          NaN                           NaN
5                          NaN                           NaN
6                          NaN                           NaN
7                          NaN                           NaN
8                          NaN                           NaN
9                          NaN                           NaN
10                         NaN                           NaN
11                         NaN                           NaN
12                         NaN                           NaN
13                         NaN                           NaN
14                         NaN                           NaN
15                         NaN                           NaN
16                         NaN                           NaN
17                         NaN                           NaN
18                         NaN                           NaN
19                         NaN                           NaN
20                         NaN                           NaN
21                         NaN                           NaN
22                         NaN                           NaN
23                         NaN                           NaN
24                         NaN                           NaN
25                         NaN                           NaN
26                         NaN                           NaN
27                         NaN                           NaN
28                         NaN                           NaN
29                         NaN                           NaN
30                         NaN                           NaN
31                         NaN                           NaN
32                         NaN                           NaN
33                         NaN                           NaN
34                         NaN                           NaN
35                         NaN                           NaN
36                         NaN                           NaN
37                         NaN                           NaN
38                         NaN                           NaN
39                         NaN                           NaN
40                         NaN                           NaN
41                         NaN                           NaN
42                         NaN                           NaN
43                         NaN                           NaN
44                         NaN                           NaN
45                         NaN                           NaN
46  COUNT CITIZEN STATUS TOTAL  PERCENT CITIZEN STATUS TOTAL
47                          44                           100
48                          35                           100
49                           1                           100
50                           0                             0
51                           2                           100
52                           6                           100
53                           1                           100
54                           2                           100
55                           0                             0
56                           3                           100

                         Unnamed: 39                         Unnamed: 40  \
0                                NaN                                 NaN
1                                NaN                                 NaN
2                                NaN                                 NaN
3                                NaN                                 NaN
4                                NaN                                 NaN
5                                NaN                                 NaN
6                                NaN                                 NaN
7                                NaN                                 NaN
8                                NaN                                 NaN
9                                NaN                                 NaN
10                               NaN                                 NaN
11                               NaN                                 NaN
12                               NaN                                 NaN
13                               NaN                                 NaN
14                               NaN                                 NaN
15                               NaN                                 NaN
16                               NaN                                 NaN
17                               NaN                                 NaN
18                               NaN                                 NaN
19                               NaN                                 NaN
20                               NaN                                 NaN
21                               NaN                                 NaN
22                               NaN                                 NaN
23                               NaN                                 NaN
24                               NaN                                 NaN
25                               NaN                                 NaN
26                               NaN                                 NaN
27                               NaN                                 NaN
28                               NaN                                 NaN
29                               NaN                                 NaN
30                               NaN                                 NaN
31                               NaN                                 NaN
32                               NaN                                 NaN

In [8]:
df = df.iloc[46:]
df

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
46,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
47,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
48,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
49,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
50,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill-formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and the commas within those fields themselves. For example, we could have a table like this:  

`ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765`

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
`"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"`

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled `'Yelp_Reviews_Corrupt.csv'`. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [ ]:
# Hint: Here's a useful programming pattern to use
try:
    # Do something
except Exception as e:
    # Handle your exception e

## Summary

Congratulations, you now practiced your Pandas-importing skills.